name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
        wget https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz
        tar -xf graphviz.tar.gz
        cd graphviz-2.40.1
        ./configure
        make
        make install
        cd ..
        cmake .
        make
